package BancOrt;

public enum Estado {
    DEPOSITO_REALIZADO,
    DEPOSITO_NO_REALIZADO,
    DEPOSITO_PARCIAL_REALIZADO,
    EXTRACCION_REALIZADA,
    SALDO_INSUFICIENTE,
    OPERACION_NO_DISPONIBLE
}
