package Gimnasio;

public enum Resultado {
    EL_SOCIO_YA_EXISTE, SOCIO_AGREGADO_CON_EXITO, NO_EXISTE_EL_SOCIO, SOCIO_DADO_DE_BAJA, EL_SOCIO_TIENE_DEUDA,
    CAMBIO_DE_ESTADO_EN_SOCIO, NO_SE_CAMBIO_EL_ESTADO
}
